### ISSUE TITLE
Use a designated list of terms for tempo

### ISSUE THREAD

**Issue by zpine1** [zpine1/deejays#1]
I would like to use a designated list of terms for tempo, just as we have for genre. It could be implemented the same way as genre (having the admin input a list), or, if it's easier, just use this list: ambient, very slow, slow, medium-slow, medium, medium-fast, fast, very fast, varies

**Comment by dancinglightning** [comment]
I would leave this to later, until you have cleaned up the data.
Otherwise you get into the same issues as with the genres, having two fields or searches that don't return anything.

We can do your list for new ones if you want?

**Comment by zpine1** [comment]
You said "We can do your list for new ones if you want?" I think that means that for new song entries, and for edits of old songs, we have to use the categories on the list. Is that right? If so, I'd like that!

**Comment by dancinglightning** [comment]
I was suggesting the new list only for *new* songs. But both is possible with a little more effort, ok.
I'll do that next.

**Comment by zpine1** [comment]
OK, great.

**Comment by dancinglightning** [comment]
Managed to do this, but that means when you edit now, you *have* to choose one of the list.
The old tempo is shown in the label as a guide.

Also a technical sideline: When you search you get the dropdown, but because the list does not contain unique words, the searches will contain "wrong", ie unexpected, results.
Eg, if you search for "fast" , the results will contain "medium fast" and all other entries where fast is mentioned (ie "gets faster").

The only way to get rid of those results is by making the search an *exact* search, but then it won't work for the old data anymore. So we can do that when you have fixed all the old data.
