### ISSUE TITLE
Show full urls for links on song list.

### ISSUE THREAD

**Issue by zpine1** [zpine1/deejays#16]
Link should be fully displayed on songs list so users know what they are clicking. For an example, see the link for the song Morphine by user Jean. It reads as "be/CQSV21c-C-c" rather than the full link "https://youtu.be/CQSV21c-C-c" .  I know the full link will be longer. I think it's fine to let it wrap a lot.

**Comment by dancinglightning** [comment]
It currently takes the domain name as the text, for www.youtube.com it will take youtube.
I can fix those short urls to use youtu , or use the toplevel (.com) as well.
So that would be youtu.be or youtube.com

You get the full link by hovering over the link. 
I would not do the full link, it will break the layout badly, some of them are really long.
I'll switch than on on the next release so you see.

**Comment by dancinglightning** [comment]
check it out. looks bad

**Comment by zpine1** [comment]
OK, I agree that the full links look bad. Displaying the full link on hover is a help. I just want users to have some idea of where they are being taken in advance. I like the "youtu.be" type format (no need for .com, etc).
